### ISSUE TITLE
Escaping issue trying to implement `Base.clipboard` for Pluto notebooks

### ISSUE THREAD

**Issue by ericphanson** [MechanicalRabbit/HypertextLiteral.jl#10]
Hello,

I'm trying to implement an analog of Base's `clipboard` function to take a string as input and copy it to the user's clipboard, but for use in Pluto notebooks. I can't use `Base.clipboard` because the Pluto server might be a remote machine (and might not have `xsel` or `xclip` installed). I thought to instead use javascript since the notebook is already running in the user's browser. My attempt is this:
```julia
using HypertextLiteral
function my_clipboard(str)
    return @htl("""
	<script>
	navigator.clipboard.writeText(`$str`)
	</script>
	""")
end
```
which seems to work as long as `str` doesn't include any `'s in it. I wasn't sure if this was the right repo for the issue-- in fact, I'm not sure if it's an issue or if I'm just using it wrong-- but I thought maybe this would be a good place to ask for how to fix it.

**Comment by clarkevans** [comment]
Hi.  I didn't implement escaping for `script` tag yet.  Perhaps I can get that done this upcoming weekend? I was thinking I could expand variables as Javascript, ie, strings would be strings.  In this case, you'd just use `writeText($str)`.

**Comment by ericphanson** [comment]
cool, that would be great! No rush here, just wanted to try it out 🙂.

Should I close this then, or leave it open as a feature request?

**Comment by clarkevans** [comment]
It's just fine as is.  Thanks.  Currently, I think no escaping will happen within script tag.  However, since we do know the context, it won't be hard to provide relevant escaping (and have it dispatchable so you could serialize any object).

**Comment by clarkevans** [comment]
@ericphanson I added support for escaping within `<script>` tag, but I haven't tagged yet.  The following should work if you don't mind verifying?  The objective is to treat `$var` as a Javascript expression, not as a string, converting Julia to Javascript.  Hence if `str` is a `String`, then, it should be rendered as a double-quoted value, no quotes in the template needed.

```
using HypertextLiteral
function my_clipboard(str)
    return @htl("""
	<script>
	navigator.clipboard.writeText($str)
	</script>
	""")
end
```

**Comment by clarkevans** [comment]
@ericphanson This is now tagged.  Please let me know if it works for you.

**Comment by ericphanson** [comment]
Just tried it, and it works great, thank you! Sorry for not responding sooner.

For the particular `clipboard` usage, I ended up switching to having a button to explicitly copy it, with
```julia
function copyable(obj, str = gh_string(obj))
	if length(str) > 10_000
		str = "Error: Object prints as more than 10k characters!"
	end
    return @htl("""
		<script>
		const button = currentScript.parentElement.querySelector("button")
		const pre = currentScript.parentElement.querySelector("pre")
		button.addEventListener("click", () =>
			navigator.
				clipboard.
				writeText(pre.innerHTML)
		)
		</script>
		<button>copy markdown</button>
		<pre style="display:none">$str</pre>
		<div>$obj</div>
	""")
end
```
(which @pankgeorg kindly helped me with on the Pluto channel in the Julia slack)
using a helper function
```julia
function gh_string(obj)
	mimes = (MIME"text/gh_markdown"(), MIME"text/markdown"(), MIME"text/plain"())
	i = findfirst(mime -> Base.showable(mime, obj), mimes)
	str = isnothing(i) ? "" : sprint(io -> show(io, mimes[i], obj))
	return str
end
```
(where `text/gh_markdown` is a MIME type I made up to try to render stuff like small dataframes in a way I could copy to github issues). I think for the purpose of interacting with the clipboard, having a button is better because it's kind of unexpected to have your clipboard populated reactively when the code changes, but maybe there is some clever use-case for that :D. But I think also having the JS escaping working might make for some interesting other use-cases too! Thanks a lot for this nice tool.
