### ISSUE TITLE
Problems with the String output of pretty_table from PrettyTables.jl in Pluto cell

### ISSUE THREAD

**Issue by disberd** [MechanicalRabbit/HypertextLiteral.jl#11]
I am not sure whether this issue should be filed here on on PrettyTables, but basically using the @htl macro on the String output from the pretty_table functions doesn't correctly renders the HTML in a pluto cell, but simply puts the HTML code inside the text of the pluto output.

The same string is correctly parsed by the HTML() function.

Here is an example:

![image](https://user-images.githubusercontent.com/12846528/120364723-e04bfe80-c30d-11eb-8d6f-a75e6e8963c6.png)

I don't know whether this is expected or if it is indeed an issue that was not known.

**Comment by clarkevans** [comment]
My guess is that PrettyTables isn't implementing `show(obj, "text/html")`.

**Comment by clarkevans** [comment]
So, I opened a ticket over in `PrettyTables` with this detail.  I hope this helps.

**Comment by clarkevans** [comment]
Oh.  I see why you've thought this way.  Hmm.  I hadn't thought of `@htl` used in this manner.  Let me investigate further.

**Comment by disberd** [comment]
@clarkevans, thanks for the prompt reply and overall for the package that seems awesome.
I indeed filed the issue here while probably it is more relevant to the other package.

At default PrettyTables prints the html directly to the stdout and I didn't find a way to provide a custom io rathern than stdout.
In some discussion I was seeing the suggestion of using the form I put above `HTML(pretty_table(String,...))` for correctly displaying on Pluto and given that this package seems to be just better in every aspect with respect to the standard `HTML` function I just tried to translate it directly.

I was in a bit of rush to get results so I didn't go too much into the documentation details of both packages so I will do that now that I have some more time and hopefully give more context.

**Comment by clarkevans** [comment]
Thank you for reporting this.  I can see how this was confusing, moreover, the behavior was incorrect.  I was treating the argument as a callable expression returning value that should be escaped.  What you have is a function that is returning a string.  The macro actually needs a string literal, not a string value or a function returning a string.  So, I've fixed this issue... by raising an error.

https://github.com/MechanicalRabbit/HypertextLiteral.jl/commit/5f3543e756d58ab1a187d92e35961f0103c1f049

...

One option I considered (but rejected) is to evaluate the expression immediately, and then use the `String` result of that expression as a template, e.g.

```
expr = __module__.eval(code)
```

However this creates the opportunity for perhaps unintended outcomes, as [described](https://julialang.zulipchat.com/#narrow/stream/225542-helpdesk/topic/Macro.20design/near/190302244) by Mason Protter.

```
julia> macro whichtype(code)
          if isa(code,Symbol) && isdefined(__module__,code)
             return typeof(__module__.eval(code))
          end
          return esc(code)
       end
@whichtype (macro with 1 method)

julia> n = 1
1

julia> @macroexpand foo(n) = @whichtype n
:(foo(n) = begin
          #= REPL[99]:1 =#
          Int64
      end)
```

I think if someone wishes to to dynamically build a template, they might use `@htl_str()` instead.

**Comment by disberd** [comment]
Thanks for the clarification.

In the end, in case someone has a similar issue, for my use case I realized I could achieve my functionality by writing:
```julia
s = pretty_table(String,args...)
eval(:(@htl $s))
```
